volumes:
  mysql:
  project:
  results:
  secrets:
  letsencrypt:

services:
  mysql:
    container_name: "mcath_mysql"
    build:
      context: images/mysql
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"

  makeproject:
    container_name: "mcath_mkproject"
    build:
      context: images/makeproject
      args:
        - BOINC_USER
        - PROJECT_ROOT
    depends_on:
      - mysql
    volumes:
      - "project:$PROJECT_ROOT.dst"
      - "secrets:/run/secrets"
    environment:
      - URL_BASE
      - PROJECT

  apache:
    container_name: "mcath_boinc"
    build:
      context: images/apache
      args:
        - BOINC_USER
        - PROJECT_ROOT
    ports:
      - "80:80"
    hostname: $PROJECT
    depends_on:
      - mysql
    volumes:
      - "project:$PROJECT_ROOT"
      - "results:/results"
      - "secrets:/run/secrets"
      - "/dev/null:/run/secrets/keys/code_sign_private"
      - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true
    environment:
      - URL_BASE
      - PROJECT
    networks:
      - default